
version: 2

models:
  - name: intermediate
    columns:
      - name: datetime
        tests:
          - not_null
          - unique
      - name: price
        tests:
          - not_null
      - name: market_cap
        tests:
          - not_null
      - name: total_volume
        tests:
          - not_null
  - name: marts
    columns:
      - name: datetime
        tests:
          - not_null
          - unique
      - name: price
        tests:
          - not_null
      - name: low
        tests:
          - not_null
      - name: high
        tests:
          - not_null
      - name: open
        tests:
          - not_null
      - name: close
        tests:
          - not_null
